const nodemailer = require('nodemailer');
require('dotenv').config();

const transporter = nodemailer.createTransport({
    service: 'gmail', // You can use other services like Outlook, Yahoo, etc.
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

const sendWelcomeEmail = async (userEmail, userName) => {
    try {
        const mailOptions = {
            from: `"UniSkills" <${process.env.EMAIL_USER}>`,
            to: userEmail,
            subject: 'Welcome to UniSkills Ecosystem! 🚀',
            html: `
                <div style="font-family: Arial, sans-serif; background: #07090f; color: #ffffff; padding: 30px; border-radius: 12px; max-width: 600px; margin: auto; border: 1px solid #3b82f6;">
                    <h1 style="color: #60a5fa; text-align: center;">Welcome to UniSkills!</h1>
                    <p style="font-size: 16px; line-height: 1.5; color: #e2e8f0;">
                        Hi <strong>${userName}</strong>,<br><br>
                        We are thrilled to have you on board! The UniSkills ecosystem is designed to connect students and mentors securely, empowering you to share knowledge and build your career portfolio.
                    </p>
                    <div style="background: rgba(59, 130, 246, 0.1); padding: 15px; border-left: 4px solid #3b82f6; margin-top: 20px;">
                        <p style="margin: 0; color: #94a3b8;">
                            <strong>Next Steps:</strong> Complete your profile, upload your resume, and start requesting or offering mentorship sessions!
                        </p>
                    </div>
                    <p style="font-size: 14px; margin-top: 30px; text-align: center; color: #64748b;">
                        Securely generated by UniSkills System.<br>
                        Have questions? Reach out to our AI Assistant on your dashboard.
                    </p>
                </div>
            `
        };

        const info = await transporter.sendMail(mailOptions);
        console.log("🟢 Welcome Email sent successfully: " + info.response);
        return true;
    } catch (error) {
        console.log("🔴 Error sending Welcome Email: ", error);
        return false;
    }
};
const sendSessionRequestEmail = async (mentorEmail, mentorName, studentName, topic, credits) => {
    try {
        const mailOptions = {
            from: `"UniSkills Mentorship" <${process.env.EMAIL_USER}>`,
            to: mentorEmail,
            subject: 'New Mentorship Request! 🔔',
            html: `
                <div style="font-family: Arial, sans-serif; background: #07090f; color: #ffffff; padding: 30px; border-radius: 12px; max-width: 600px; margin: auto; border: 1px solid #10b981;">
                    <h1 style="color: #34d399; text-align: center;">New Request Received</h1>
                    <p style="font-size: 16px; line-height: 1.5; color: #e2e8f0;">
                        Hi <strong>${mentorName}</strong>,<br><br>
                        Great news! <strong>${studentName}</strong> has just requested a mentorship session with you.
                    </p>
                    <div style="background: rgba(16, 185, 129, 0.1); padding: 15px; border-left: 4px solid #10b981; margin-top: 20px;">
                        <p style="margin: 5px 0; color: #94a3b8;"><strong>Topic:</strong> ${topic}</p>
                        <p style="margin: 5px 0; color: #94a3b8;"><strong>Offered Credits:</strong> 🪙 ${credits}</p>
                    </div>
                    <p style="font-size: 14px; margin-top: 30px; text-align: center; color: #64748b;">
                        Go to your Dashboard to Accept or Decline the request.<br>
                        UniSkills Ecosystem.
                    </p>
                </div>
            `
        };

        const info = await transporter.sendMail(mailOptions);
        console.log("🟢 Session Request Email sent successfully: " + info.response);
        return true;
    } catch (error) {
        console.log("🔴 Error sending Session Request Email: ", error);
        return false;
    }
};

const sendPasswordResetEmail = async (userEmail, userName, resetLink) => {
    try {
        const mailOptions = {
            from: `"UniSkills Security" <${process.env.EMAIL_USER}>`,
            to: userEmail,
            subject: 'Password Reset Request 🔐',
            html: `
                <div style="font-family: Arial, sans-serif; background: #07090f; color: #ffffff; padding: 30px; border-radius: 12px; max-width: 600px; margin: auto; border: 1px solid #ef4444;">
                    <h1 style="color: #f87171; text-align: center;">Reset Your Password</h1>
                    <p style="font-size: 16px; line-height: 1.5; color: #e2e8f0;">
                        Hi <strong>${userName}</strong>,<br><br>
                        We received a request to reset the password for your UniSkills account. If you didn't make this request, you can safely ignore this email.
                    </p>
                    <div style="text-align: center; margin: 30px 0;">
                        <a href="${resetLink}" style="background: linear-gradient(135deg, #ef4444, #b91c1c); color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 16px;">Reset Password</a>
                    </div>
                    <p style="font-size: 14px; margin-top: 30px; text-align: center; color: #64748b;">
                        This link will expire in 15 minutes.<br>
                        Securely generated by UniSkills System.
                    </p>
                </div>
            `
        };

        const info = await transporter.sendMail(mailOptions);
        console.log("🟢 Password Reset Email sent successfully: " + info.response);
        return true;
    } catch (error) {
        console.log("🔴 Error sending Password Reset Email: ", error);
        return false;
    }
};

module.exports = {
    sendWelcomeEmail,
    sendSessionRequestEmail,
    sendPasswordResetEmail
};
